# Generate a service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sd-on-eks-compare-backend
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-on-eks-compare-backend
  labels:
    app: sd-on-eks-compare-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-on-eks-compare-backend
  template:
    metadata:
      labels:
        app: sd-on-eks-compare-backend
    spec:
      serviceAccountName: sd-on-eks-compare-backend
      containers:
      - name: sd-on-eks-compare-backend
        image: 600413481647.dkr.ecr.us-west-2.amazonaws.com/sd-on-eks-compare/backend:1.3
        imagePullPolicy: Always
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"
        - name: DYNAMODB_TABLE_NAME
          value: "sd-image-generation-tasks"
        - name: SQS_OUTPUT_QUEUE_URL
          value: "https://sqs.us-west-2.amazonaws.com/600413481647/sdoneksOutputQueue"
        - name: SD_API_KEY
          value: "bu2J4QVDxy9g3tP3aHWhW1NCvhCsya7j9yTMktRl"
        - name: SD_API_ENDPOINT
          value: "https://e1lcc5lji3.execute-api.us-west-2.amazonaws.com/dev/v1alpha2"
        - name: CF_URL
          value: "https://d49x78c4g79qn.cloudfront.net/"
        - name: LOGLEVEL
          value: "INFO"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sd-on-eks-compare-backend-service
  labels:
    app: sd-on-eks-compare-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: sd-on-eks-compare-backend
